#!/bin/bash
WATERMARK=$2;
COVEROUT=`go test -cover $1`;
arrIN=(${COVEROUT/// });
COVERLEVEL=`echo ${arrIN[4]} | tr "%" " "`;
COVERLEVEL=${COVERLEVEL/.*};
echo "Coverage - ${COVERLEVEL}%";
echo "Watermark- ${WATERMARK}%";
if [[ $COVERLEVEL -lt $WATERMARK ]]; then (exit 1); fi
