#!/bin/bash
WATERMARK=90;
COVEROUT=`go test -cover ./src/itertools/...`;
arrIN=(${COVEROUT/// });
COVERLEVEL=`echo ${arrIN[4]} | tr "%" " "`;
COVERLEVEL=${COVERLEVEL/.*};
echo "Coverage - ${COVERLEVEL}%";
echo "Watermark- ${WATERMARK}%";
if [[ $COVERLEVEL -lt $WATERMARK ]]; then (exit 1); fi
